# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
title: Melania Andrisan
email: mela@mela.com
description: > # this means to ignore newlines until "baseurl:"
  My technical experience
# baseurl: "melaniaandrisan.github.io/" # the subpath of your site, e.g. /blog
# url: "http://melaniaandrisan.github.io/melaniaandrisan.github.io" # the base hostname & protocol for your site
twitter_username: melaniadanciu
github_username:  melaniaandrisan

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty

# Post excerpt
---
excerpt_separator: <!--more-->
---

Excerpt
<!--more-->
Out-of-excerpt
